---
- hosts: demo
  tasks:
        - name: Create a cron job
          cron:
                name: "Clear lastlog"
                minute: "0"
                hour: "0"
                job: echo "" > /var/log/lastlog
