---
- hosts: demo
  tasks:
        - name: Create a cron job
          cron:
                name: "Free memory Check"
                minute: "0"
                hour: "*/2"
                job: "sh /root/free.sh"
